### ISSUE TITLE
API capabilities/reponsabilities

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#11]
Currently the API is so simple essentially based on a middleware pluggable interface. I'd prefer keeping vinci API simple as possible with a useful but limited set of methods.

However, I think there should be provided additional method to perform recurrent actions, such as defining the server to forward or the URLs to replay traffic.

Also, vinci API could implicitely provide its own router in order to provide a simple and prebuilt way to declare routes in your server without explicitly importing new packages. Of course, you should be able to use you own router/muxer, but vinci should provide its own as optional.

I'm talking about adding the following methods:
Get(path)
Post(path)
Put(path)
Delete(path)
Patch(path)
Route(method, path)
Forward(url)

From the other side, this is purely convenience and not useful for everything, since encapsulation hides features thst might be useful for an API consumer, for instance, using the route-level middlaware chain,

There are tradeoff on this, and the decision should balance between API simplicity, versatility and convenience.

**Comment by h2non** [comment]
Trying to extend this a little bit, here is a code showcase:

With this proposal we will have:
```go
proxy := vinci.NewServer(opts)

route := proxy.Get("/foo/:bar")
route.Use(someRouteMiddleware)
route.Use(anotherRouteMiddleware)

route := proxy.Post("/foo/:bar")
route.Use(someRouteMiddleware)
route.Use(anotherRouteMiddleware)

proxy.Listen()
```

Alternatively, we can have the same layer but importing the router third-party package which is 
```go
proxy := vinci.NewServer(opts)

route := proxy.Get("/foo/:bar")
route.Use(someRouteMiddleware)
route.Use(anotherRouteMiddleware)

route := proxy.Post("/foo/:bar")
route.Use(someRouteMiddleware)
route.Use(anotherRouteMiddleware)

proxy.Listen()
```

In essence, should we provide a default embedded router as part of vinci's core and it's API, or instead force the developer to import its custom router. Even with the first approach the developer is able to use its preferred router/mux layer. They only won't use the built-in router in vinci's core.

**Comment by h2non** [comment]
Update: refresh the page, the code above has been edited.

**Comment by h2non** [comment]
@vinci-proxy/core I would appreciate some opinions here.

**Comment by groyoh** [comment]
The first version seems more convenient to me. If I use a library, I want it to be as convenient as possible.I think most people wouldn't want/need to define/import a custom router.

**Comment by zzarcon** [comment]
+1 for providing the router in the same library, honestly I can't see any use case of the library that doesn't need a router

**Comment by h2non** [comment]
This was already supported. Closing due to deprecation.
