### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#12]
We are still on time on this. I was thinking that we can rename the project name into another which has no direct (or even less) trademarks protections. Especially in case that we want to use the project for some comercial purposes, such as provinding premium saas services, pay-per-use components etc...

Without changing too much the fonetic, we could use (just to give you a few):
- vincy
- vinix
- vinxy
- vinxi

Also, we should use standalone Github organization name with out even adding -proxy or stuff like that.

Opinions? @vinci-proxy/core

**Comment by groyoh** [comment]
Did https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.rrf4u36oh made you think about this? :smile:
I would go for `vincy`. Phonetic stays the same and I like how it sounds. Right now I don't have better name in mind but I'll think about it.

**Comment by h2non** [comment]
I already know about the npm issue, but here we're not using any private solution to distribute the software, instead we are just using Github which is also private but more open.

My concerns are more focused on future legal stuff about using the project for comercial purposes, so I'd prefer keeping the name as unique as possible.

My new proposal is to rename it into: vinxi or vinxy

**Comment by groyoh** [comment]
Would you still pronounce it as `vincy`? Otherwise I find it difficult to pronounce `vinXi`.

**Comment by h2non** [comment]
The phonetic changes a bit, but not too much. See the text-to-speech:
https://translate.google.es/#en/es/vinxi

**Comment by h2non** [comment]
Just to move forward with the discussion, I think `vinxi` would be better for the following benefits:
- Almost unique name in every ecosystem.
- Github organization name available.
- More cheap TLD (since it's less popular word).
- Phonetic is similar to `vinci`. 
- Has not pronunciation constraint in common languages. 
- No copyright or trademark issues.
- Keeps the same project name length.

As cons I consider:
- It's less cool than `vinci.
- Has to rename a lot of things.

Feel free to share your proposal. Radical new project names are welcomed as well.
After the final discussion, I'll perform the required name changes.

**Comment by groyoh** [comment]
I really liked vinci. So vinxi is a good choice for me. As a side note `vinxi` is almost not pronounceable in French :smile:

**Comment by h2non** [comment]
Oops! For cases like that we should fallback to English pronunciation, which is clear enough.

Any other proposal? We're in time ;)

**Comment by groyoh** [comment]
Unfortunately, I don't have any better proposal. :disappointed:

**Comment by h2non** [comment]
What about `vincd` or `vinxd`

**Comment by groyoh** [comment]
It's quite hard to figure out how to pronounce it.

**Comment by h2non** [comment]
@zzarcon Some opinions or final proposals here?

**Comment by zzarcon** [comment]
Honestly I prefer `Vinci`, but it's true all the points you mentioned before... So, in the case of we can not use it I will go for `vinxi`, sounds also pretty good to me

**Comment by h2non** [comment]
I'll give myself tonight to think about this and will take the final decision tomorrow.

**Comment by h2non** [comment]
Final round, I promise.

- gooxy
- goward
- hooxy
- mcury
- tingo
- borxy

**Comment by groyoh** [comment]
None of these sounds nice to me, sorry :smile: Maybe `mcury` if pronounced as `mercury`.

**Comment by h2non** [comment]
Thanks for the comments. Project renamed to `vinxi`. I'm changing the repos, config and old references to `vinci`. I would recommend you to use the [dev](https://github.com/vinxi/dev) repository.
