### ISSUE TITLE
Generic logging layer

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#14]
Providing a generic logging layer would be fine, but I'm not quite sure how to provide it transversally across vinxi's components.

We could argue about providing a short of convetions to write idiomatic components following similar patterns and ways to do things, but that won't be fully valid when using third-party middlewares.

My opinion is about providing some facilities, but not impositions, so the devs should pick the layer that they do prefer for logging.

The logging/trace component should provide implicit logging capabilities, but limited to HTTP protocl domain (methods, headers, body length, response time...)

**Comment by h2non** [comment]
@groyoh some discussion is still required here. I'm not sure about supporting this feature as part of `vinxi` core API. My opinion at this time would be don't support anything specific that implies growing the API contract and based on the needs and dev requests in the future consider supporting it or not.

**Comment by groyoh** [comment]
@h2non I think waiting for the implementation is a wise choice since right now we don't really know how this package will evolve. To me there should be some built-in logic for logging whether it's now or in the future. But we can figure it out at a later point.

**Comment by h2non** [comment]
I totally agree.

**Comment by h2non** [comment]
Closing for now, since it out of scope. We can reopen the discussion in the future.
