### ISSUE TITLE
Default proxy handler behavior

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#15]
Currently, when you create a proxy, the default final HTTP traffic handler will be [this one](https://github.com/vinxi/layer/blob/master/layer.go#L20-L23).
Dev should call `vinci.Forward("http://target.com")` to start forwarding traffic to another server.

I think this behavior is not convenient since we're inside a proxy domain, meaning it should do something by default with the traffic. One idea might using the default `forwarder` handler, which will finally determine if it's able to route and forward the traffic.

The intrinsic problem here is that you need to call `vinci.Forward()` always, but in some scenarios, like using service discovery, is not necessary since you'll dynamically define the target server to forward traffic, instead of statically define it.

**Comment by h2non** [comment]
@vinxi/core Some opinions here would be appreciated.

**Comment by h2non** [comment]
By the default the proxy won't be able to route traffic unless the target server URL is defined via `.Forward()` or via middleware/plugin. I believe this is the most coherent behavior. In case that no target URL is defined, the server will reply with a `502 Bad Gateway` error.

**Comment by groyoh** [comment]
If I get your last comment, you want to keep the current default behavior, right?

**Comment by h2non** [comment]
That's correct. Feel free to share your opinion about this. We're very open to change this as anytime.

**Comment by groyoh** [comment]
To me that makes sense but I would rather change it to a `501 Not Implemented` maybe.

**Comment by h2non** [comment]
That makes sense, but not fully sure using it in a proxy context. In any case, the response body should provide human focused error details to make the error more understandable.

**Comment by groyoh** [comment]
According to the spec:

> 10.5.2 501 Not Implemented

> The server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource.

> 10.5.3 502 Bad Gateway

> The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request.

To me `502` means that the call to the upstream server was done but failed.

**Comment by h2non** [comment]
Thanks for the copy. 

I believe that the RFC spec is a bit ambiguous in terms for HTTP status code usage definitions. If you see the W3C spec the spec defines another sort of usage for those statuses. 

According to the RFC spec I should overload the use of `502` responses for any invalid server response (perhaps `> 500`) without forwarding the original server response status. On the other hand, it doesn't mention any sort of applicability on scenarios for network originated errors, which are lower than L7 communication level. In reality, this is typically when the `502` is actually used in most proxy servers: when the communication with the target server cannot be performed, let's say because a network error due to bad routing, no DNS resolution, high jitter latency, L3 NACK response..., but the spec doesn't explicitly mention that. Should I reply with a `500` in that case? Due to the generalization of HTTP REST patterns, the status codes gain a lot more of responsibility and relevance today, but I believe there's still a level of ambiguity with certain particular cases where the industry don't a clear consensus coverage, and the standards spec reflects this. Perhaps if the different standard specs (such as RFC) adopts some sort of wiki concepts to improve it from time to time with a community-driven philosophy, it will be better in a lot of senses.

Well, just sharing my perspective as reflexion, but I want to say that I don't disagree with your proposal, indeed, we would very possible use it, also using a proper response body message that clearly exposes the nature of the error.

**Comment by groyoh** [comment]
From this point of view I agree that 502 could be used. In such case, I'd say go for what feels better to you. :wink:

**Comment by h2non** [comment]
The conclusion of the discussion has been taken during the implementation. Closing.
