### ISSUE TITLE
Plugin / Provider layer

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#16]
This is more than a simple middleware handler. Plugin can provide behavior and features to the proxy and most importantly, to another components. Middleware handler are by default closed to external modification, at least via internal vinxi API.

This requires some discussion.

**Comment by h2non** [comment]
I was thinking about how to easily plugin components in `vinxi` ecosystem. 
My main concern is about generic features that are usually recurrent in third-party components, such as logging, metrics etc...

The questions are:
- Do we need a generic, convension-focused way to do common tasks across `vinxi` components?
- Do we need a generic layer to do logging?
- Do we need a generic layer to do logging?

Generalization has always constrains and is not fully convenient for every one. Also, introducing it as part of the library core could be confusing a bad choice in the future when we realize. Also, keeping things simple in the future can enable more.

One idea might be implementing some sort of inversion of control / dependency provider to allow components to optionally register and use the generic layer (logging, metrics....). 

The interfaces could be:
```go
type ServiceProvider interface {
  Logger() Logger
  Metrics() Metrics
  Context() Context
}

type Provider interface {
  Provide(ServiceProvider)
}
```

An implementation would look like this:
```go
// Provide will be indirectly executed when the plugin is registered.
func (c *Component) Provide(p layer.ServiceProvider) {
  c.logger = p.Logger()
  c.metrics = p.Metrics()
}

func (c *Component) HandleHTTP(w http.ResponseWriter, r *http.Request, h http.Handler) {
  c.logger.Println("component called") // test logger
  h.ServeHTTP(w, r)
}
```

**Comment by h2non** [comment]
@vinxi/core Looking for some opinions.

**Comment by groyoh** [comment]
If I get your idea, `ServiceProvider` would basically be third parties implementing their own logic? Is `Provider/Component` from the third-party or from the user? When the `ServiceProdiver` provides a `Logger` and not a `Metrics`, is a default `Metrics` provided? Do the user have to check that these elements are available?

**Comment by h2non** [comment]
Mostly yes. `ServiceProvider` wll basically provide a very concrete of recurrent utilities usually consumed across `vinxi` components. We're just trying to find a proper way to act as proxy/provider in order to simplify common service consumption from plugin developers.  

To give you a better use case, in order to use a custom Logger service, you can attach it a `vinxi` instance level.
```go
v := vinci.New()
vinci.UseLogger(myCustomLoggerProvider)
```

Then you can use it as I described before in the example to use the `Logger` via `ServiceProvider` injector. 

As you can imagine, this could be useful in some scenarios, but not always. Also, forces to extend the interface contract of the API with perhaps not fully usable methods, I'd tend to simplify interfaces as maximum as possible. 

Also, I believe that if we want to move forward with this feature we should consider using dependency injection, which will make this really powerful. In this case the reflection performance cost is only applied during plugin binding, not during middleware call chain. 

There're some small and useful implementations in Go from the community, but I would like to have something like I created [here](https://github.com/h2non/injecty) in JavaScript.

**Comment by h2non** [comment]
This discussion can be considered as deprecated now.
