### ISSUE TITLE
Create throttle component

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#18]
Posibly use (used by myself in production for a while and worked fine): 
@groyoh if you are motivated enough, you can take care of this.

https://github.com/throttled/throttled

**Comment by groyoh** [comment]
What's the main difference with https://github.com/vinxi/ratelimit?

**Comment by h2non** [comment]
It's the end is pretty much the same, but that package provides a more HTTP specific features, including Retry-After headers and so on. Also, it's configuration possibilities are better and versstile, also for specific traffic filtering and further rules. At some point perhaps makes sense to only maintain one package. I initially forget about this one, but I actually used it for a while in other Go projects.

**Comment by groyoh** [comment]
Alright, I'll take a deeper look at it then.

**Comment by h2non** [comment]
@groyoh Up to you with this. There's no rush. Feel free to create a new repo for this and create the package from scratch.

**Comment by groyoh** [comment]
I'll try to get this done this week. I've been pretty busy the last few weeks.

**Comment by h2non** [comment]
Moving this into vinxi/throttle. Create the repository.
