### ISSUE TITLE
Simplify Rule/Plugin interfaces

### ISSUE THREAD

**Issue by h2non** [vinxi/vinxi#22]
Just a brief discussion about interfaces simplification.

Current `Rule` interface:
```go
type Rule interface {
    ID() string
    Name() string
    Description() string
    JSONConfig() string
    Match(*http.Request) bool
}
```

Possible proposal:
```go
type Rule interface {
    ID() string // returns the unique alphanumeric rule identifier, used for external API querying (e.g: HTTP API)
    Metadata() map[string]interface{} // Exposes an interface agnostic rule metadata (encapsulates name, description and further common fields). Cons: Implies explicit type casting.
    Config() string || map[string]interface{} // Rule config. Could be stored as JSON. Same goes for Plugins. Used to retrieve Rule config fields to review, modification and so on.
    Match(*http.Request) bool // No description required ;)
}
```

**Comment by h2non** [comment]
@groyoh Some opinion about this would be really appreciated.

**Comment by h2non** [comment]
Another question: should be the rules inmutable? I mean, once you define and register it, you can only enable/disable it or remove it, but cannot reconfigure it. This will remove the overuse of sync/locks mechanisms in the code, making rules implementation faster and safer.

I believe we should make it inmutable. Plugins should be as well.

**Comment by groyoh** [comment]
I prefer the first version better. It's more descriptive and easier to understand. I would prefer to have the config as a map in both case though.

As for your last comment, I agree that the rule should be immutable. I'd rather allow creating new immutable rule and disable existing ones rather modifying rules. In the end it makes it easier to reuse existing rule and reduce risk of errors/mistakes.

**Comment by h2non** [comment]
@groyoh When we're talking about immutability, should we even prevent enable/disable statuses? If yes, any plugin/rule/scope entity can be only registered and removed. Removing it means it cannot be reactivated again, unless you register it again with the same params. If we adopt this approach we'll simplify a lot the code and provide a better performance without using too much atomic synchronization mechanisms.

**Comment by h2non** [comment]
Plugins could also expose custom metadata fields, such as configuration settings, service details, stats etc... A method such as `Metadata() Config` to expose it would be fine.

**Comment by h2non** [comment]
Done!
